/*
=========================================================
Project       : Satellite Mission Control System
Module        : Notification
Object        : NOTIFICATION
File          : 103_NOTIFICATION_TABLE.sql
Author        : Sreerag T C
Database      : Oracle XE 11g
Version       : 1.0.0
Created On    : 25-JUL-2026
=========================================================
Description:
Stores notifications generated by the system for
authenticated users. Notifications may represent
system alerts, mission events, command execution
results or security messages.
=========================================================
*/

---------------------------------------------------------
-- Drop Table (Development Only)
---------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NOTIFICATION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

---------------------------------------------------------
-- Create Table
---------------------------------------------------------

CREATE TABLE NOTIFICATION
(
    NOTIFICATION_ID        NUMBER(10)      NOT NULL,

    USER_ID                NUMBER(10),

    TITLE                  VARCHAR2(150)   NOT NULL,

    MESSAGE                VARCHAR2(1000)  NOT NULL,

    NOTIFICATION_TYPE      VARCHAR2(30)
                           NOT NULL,

    PRIORITY               VARCHAR2(20)
                           DEFAULT 'MEDIUM'
                           NOT NULL,

    IS_READ                CHAR(1)
                           DEFAULT 'N'
                           NOT NULL,

    CREATED_TIME           TIMESTAMP
                           DEFAULT CURRENT_TIMESTAMP
                           NOT NULL,

    READ_TIME              TIMESTAMP,

    EXPIRY_TIME            TIMESTAMP,

    CREATED_AT             TIMESTAMP
                           DEFAULT CURRENT_TIMESTAMP
                           NOT NULL,

    UPDATED_AT             TIMESTAMP,

    UPDATED_BY             NUMBER(10),

    -----------------------------------------------------
    -- Constraints
    -----------------------------------------------------

    CONSTRAINT PK_NOTIFICATION
        PRIMARY KEY (NOTIFICATION_ID),

    CONSTRAINT FK_NOTIFICATION_USER
        FOREIGN KEY (USER_ID)
        REFERENCES APP_USER(USER_ID),

    CONSTRAINT FK_NOTIFICATION_UPDATED_BY
        FOREIGN KEY (UPDATED_BY)
        REFERENCES APP_USER(USER_ID),

    CONSTRAINT CHK_NOTIFICATION_PRIORITY
        CHECK
        (
            PRIORITY IN
            (
                'LOW',
                'MEDIUM',
                'HIGH',
                'CRITICAL'
            )
        ),

    CONSTRAINT CHK_NOTIFICATION_STATUS
        CHECK
        (
            IS_READ IN ('Y','N')
        ),

    CONSTRAINT CHK_NOTIFICATION_TYPE
        CHECK
        (
            NOTIFICATION_TYPE IN
            (
                'MISSION',
                'COMMAND',
                'SECURITY',
                'SYSTEM',
                'TELEMETRY'
            )
        )
);

PROMPT ===========================================
PROMPT NOTIFICATION table created successfully.
PROMPT ===========================================