/*
=========================================================
Project       : Satellite Mission Control System
Module        : Report Management
Object        : REPORT Indexes
File          : 130_REPORT_INDEX.sql
Author        : Sreerag T C
Database      : Oracle XE 11g
Version       : 1.0.0
Created On    : 25-JUL-2026
=========================================================
Description:
Indexes for efficient report retrieval.
=========================================================
*/

---------------------------------------------------------
-- Generated By
---------------------------------------------------------

CREATE INDEX IDX_REPORT_GENERATED_BY
ON REPORT(GENERATED_BY);

---------------------------------------------------------
-- Report Type
---------------------------------------------------------

CREATE INDEX IDX_REPORT_TYPE
ON REPORT(REPORT_TYPE);

---------------------------------------------------------
-- Report Status
---------------------------------------------------------

CREATE INDEX IDX_REPORT_STATUS
ON REPORT(REPORT_STATUS);

---------------------------------------------------------
-- Generated Time
---------------------------------------------------------

CREATE INDEX IDX_REPORT_GENERATED_TIME
ON REPORT(GENERATED_TIME);

---------------------------------------------------------
-- Report Format
---------------------------------------------------------

CREATE INDEX IDX_REPORT_FORMAT
ON REPORT(REPORT_FORMAT);

---------------------------------------------------------
-- Composite Index
---------------------------------------------------------

CREATE INDEX IDX_REPORT_USER_TIME
ON REPORT
(
    GENERATED_BY,
    GENERATED_TIME DESC
);

PROMPT ===========================================
PROMPT REPORT indexes created successfully.
PROMPT ===========================================