/*==========================================================
  ISTMS Database
  File : 01_DATABASE_USER.sql
==========================================================*/

-- Execute as SYS or SYSTEM

CREATE USER SATMISSION
IDENTIFIED BY satmission123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT TO SATMISSION;
GRANT RESOURCE TO SATMISSION;
GRANT CREATE VIEW TO SATMISSION;
GRANT CREATE SEQUENCE TO SATMISSION;
GRANT CREATE TRIGGER TO SATMISSION;
GRANT CREATE PROCEDURE TO SATMISSION;
GRANT CREATE TYPE TO SATMISSION;
GRANT CREATE SYNONYM TO SATMISSION;

COMMIT;